# Generated by Django 5.0 on 2023-12-29 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="video",
        ),
    ]
