# Generated by Django 5.0 on 2024-01-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0002_remove_campaign_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="donor_count",
            field=models.IntegerField(default=0),
        ),
    ]
