# Generated by Django 5.0 on 2024-01-16 16:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0003_campaign_donor_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="https://asset.cloudinary.com/dbn9ejpno/dcbb0fbcd596ecbbd4f91c9d47c7cdc7",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
