# Generated by Django 5.0.2 on 2024-03-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0005_alter_campaign_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="image",
            field=models.CharField(
                default="https://asset.cloudinary.com/dbn9ejpno/dcbb0fbcd596ecbbd4f91c9d47c7cdc7",
                max_length=255,
                null=True,
            ),
        ),
    ]
