# Generated by Django 5.0.2 on 2024-03-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0006_alter_campaign_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="raised",
            field=models.IntegerField(default=0),
        ),
    ]
