# Generated by Django 5.0.2 on 2024-03-13 22:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0010_alter_campaign_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="name",
            new_name="currency",
        ),
        migrations.AddField(
            model_name="campaign",
            name="goals_obj",
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CampaignDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="campaign.campaign",
                    ),
                ),
            ],
        ),
    ]
