# Generated by Django 5.0.2 on 2024-03-13 23:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0011_rename_name_campaign_currency_campaign_goals_obj_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="image",
        ),
        migrations.AddField(
            model_name="campaign",
            name="account_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="account_number",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="bank_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CampaignImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        blank=True,
                        default="https://asset.cloudinary.com/dbn9ejpno/dcbb0fbcd596ecbbd4f91c9d47c7cdc7",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="campaign.campaign",
                    ),
                ),
            ],
        ),
    ]
