# Generated by Django 5.0.2 on 2024-04-01 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0012_remove_campaign_image_campaign_account_name_and_more"),
        ("campaign_category", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="campaign_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="campaign_category.campaigncategory",
            ),
        ),
    ]
