# Generated by Django 5.0 on 2024-02-23 23:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customauth", "0002_customuser_first_name_customuser_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="name",
        ),
    ]
