# Generated by Django 5.0.2 on 2024-04-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customauth", "0004_customuser_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="registration_method",
            field=models.CharField(
                choices=[("email", "Email"), ("google", "Google")],
                default="email",
                max_length=10,
            ),
        ),
    ]
