# Generated by Django 5.0.2 on 2024-03-18 23:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customauth", "0003_remove_userprofile_name"),
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="donor",
        ),
        migrations.AddField(
            model_name="donation",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="donation",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="donor_id",
            field=models.ForeignKey(
                default=uuid.uuid4,
                on_delete=django.db.models.deletion.CASCADE,
                to="customauth.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="donation",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
