# Generated by Django 5.0 on 2023-12-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emailer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
